[package]
name = "w4on-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
w4on-sys = { git = "https://github.com/hnd2/w4on-sys" }
